"""
Build JSON-LD schema blocks for site articles.
Only generates FAQPage — Article and BreadcrumbList are handled by SchemaMarkup.astro at render time.
"""

import json
import re
import yaml
from pathlib import Path

ROOT = Path(__file__).parent.parent


def _get_site_url() -> str:
    cfg_path = ROOT / "site.config.yaml"
    cfg = yaml.safe_load(cfg_path.read_text())
    domain = cfg["site"]["domain"]
    return f"https://{domain}"


SITE_URL = _get_site_url()


def _load_nav() -> dict:
    nav_path = ROOT / "config/navigation.yaml"
    return yaml.safe_load(nav_path.read_text())


def _hub_to_category(hub_slug: str):
    """Return {label, slug} for the category containing hub_slug."""
    nav = _load_nav()
    for cat in nav.get("categories", []):
        for hub in cat.get("hubs", []):
            if hub["slug"] == hub_slug:
                return {"label": cat["label"], "slug": cat["slug"],
                        "hub_label": hub["label"], "hub_slug": hub["slug"]}
    return None


def parse_faq(body: str) -> list:
    """Extract FAQ Q&A pairs from article body markdown."""
    faq_section = re.search(r'## Frequently Asked Questions\s*(.*?)(?=\n## |\Z)',
                            body, re.DOTALL)
    if not faq_section:
        return []

    faq_text = faq_section.group(1)
    pairs = []

    # Split on H3 headings
    chunks = re.split(r'\n### ', faq_text)
    for chunk in chunks:
        chunk = chunk.strip()
        if not chunk:
            continue
        lines = chunk.splitlines()
        question = lines[0].strip().lstrip('#').strip()
        answer_lines = [l for l in lines[1:] if l.strip() and not l.startswith('!')]
        answer = ' '.join(answer_lines).strip()
        if question and answer:
            pairs.append({"q": question, "a": answer})

    return pairs[:5]


def build_schema(article_data: dict, body: str) -> str:
    """Build FAQPage JSON-LD schema and return as HTML string.

    Article and BreadcrumbList are generated by SchemaMarkup.astro at render time.
    """
    # ── FAQ schema ────────────────────────────────────────────────────────────
    faq_pairs = parse_faq(body)
    if not faq_pairs:
        return ""

    faq_schema = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {
                "@type": "Question",
                "name": p["q"],
                "acceptedAnswer": {"@type": "Answer", "text": p["a"]}
            }
            for p in faq_pairs
        ]
    }

    html = f'<script type="application/ld+json">\n{json.dumps(faq_schema, indent=2)}\n</script>'
    return f"\n\n{html}\n"
